services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - .env:/app/.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: ["/bin/bash"]  # Just start a shell instead of the app
    stdin_open: true  # Keep STDIN open
    tty: true        # Allocate a pseudo-TTY