services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - .env:/app/.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    networks:
      - gpt-pilot-network
    restart: unless-stopped
    command: python main.py

networks:
  gpt-pilot-network:
    driver: bridge