[build-system]
requires = ["setuptools>=69.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "gpt-pilot"
version = "0.1.0"
dynamic = ["dependencies"]

[tool.setuptools.packages.find]
include = ["core*"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }